resources:
  repositories:
    - repository: templates
      type: git
      name: DEVOPS_Platform_as_a_Service/deploy-templates
      ref: AB#543990-prevent-iam-role-sg-creation
      #ref: refs/tags/7.5.0
      # - repository: kms-key
      # type: git
      # name: DEVOPS_Platform_as_a_Service/kms-key
      # ref: refs/tags/1.1.0
      #- repository: transfer-family-lambda-IdP
      #type: git
      #name: DEVOPS_Platform_as_a_Service/transfer-family-lambda-IdP
      #ref: AB#463408-Alarms-TFEnhancement
    # - repository: RDS-Aurora-PostgreSQL-serverless
    #   type: git
    #   name: DEVOPS_Platform_as_a_Service/RDS-Aurora-PostgreSQL-serverless
    #   ref: refs/tags/1.2.0
    - repository: alarm-aggregator
      type: git
      name: DEVOPS_Platform_as_a_Service/alarm-aggregator
      ref: refs/tags/2.0.3
    - repository: sns-subtopic
      type: git
      name: DEVOPS_Platform_as_a_Service/sns-subtopic
      ref: refs/tags/2.0.1
      #- repository: grafana-prometheus
      #type: git
      #name: DEVOPS_Platform_as_a_Service/grafana-prometheus
      #ref: refs/tags/2.1.0
      # ref: AB#248528-update-situs-vpn-access-for-dev
    - repository: vpc
      type: git
      name: DEVOPS_Platform_as_a_Service/vpc
      ref: refs/tags/4.1.1
    - repository: nlb
      type: git
      name: DEVOPS_Platform_as_a_Service/nlb
      ref: refs/tags/1.7.0
    - repository: API-Gateway
      type: git
      name: DEVOPS_Platform_as_a_Service/API-Gateway
      ref: refs/tags/1.1.0
      #ref: AB#469228-factory-version
      #ref: AB#469228-first-version
      # - repository: certificate-management
      # type: git
      # name: DEVOPS_Platform_as_a_Service/certificate-management
      # ref: refs/tags/2.1.0
      #- repository: storage-gateway
      #type: git
      #name: DEVOPS_Platform_as_a_Service/storage-gateway
      #ref: refs/tags/3.6.0
    - repository: mongodb
      type: git
      name: DEVOPS_Platform_as_a_Service/mongodb
      ref: refs/tags/5.8.0
      #ref: refs/tags/5.7.1
      # ref: AB#393715-fixing-s3-deprecation
      #ref: AB#252408-MongoDB-Enterprise
    - repository: mongodb-v7
      type: git
      name: DEVOPS_Platform_as_a_Service/mongodb-v7
      ref: AB#547831-Sept-2025-update-AMI
      #ref: refs/tags/1.2.0
    - repository: s3
      type: git
      name: DEVOPS_Platform_as_a_Service/s3
      ref: refs/tags/4.2.0
    - repository: amazonmq
      type: git
      name: amazonmq
      # ref: ADO-529601
      ref: refs/tags/4.2.0
      #- repository: elasticbeanstalk
      #type: git
      #name: DEVOPS_Platform_as_a_Service/ElasticBeanStalk
      #ref: refs/tags/7.17.0
    - repository: lambdas
      type: git
      name: DEVOPS_Platform_as_a_Service/lambdas
      ref: refs/tags/3.2.0
      #- repository: SaaSNow_app_monitor
      #type: git
      #name: SAMC Shared Components/SaaSNow_app_monitor
      #ref: refs/tags/1.0.0
    - repository: eks-cluster-v11
      type: git
      name: DEVOPS_Platform_as_a_Service/eks-cluster-v11
      ref: refs/tags/3.7.0
      # - repository: fluxCIRepo
      # type: git
      # name: DEVOPS_Platform_as_a_Service/flux-app-sandbox
      # ref: AB#241049-test-ZNathanT-EFS
    - repository: ssrs-rdsmssql
      type: git
      name: DEVOPS_Platform_as_a_Service/ssrs-rdsmssql
      ref: refs/tags/13.0.0
      #- repository: synthetic-canary-alarm
      #type: git
      #name: DEVOPS_Platform_as_a_Service/synthetic-canary-alarm
      #ref: refs/tags/2.2.0
    # - repository: autoscaling
    #   type: git
    #   name: DEVOPS_Platform_as_a_Service/autoscaling
    #   ref: refs/tags/3.4.0
    - repository: rds-mssql
      type: git
      name: DEVOPS_Platform_as_a_Service/rds-mssql
      ref: refs/tags/12.0.0
      # - repository: elasticsearch
      # type: git
      # name: DEVOPS_Platform_as_a_Service/elasticsearch
      # ref: AB#323294-enhance-for-advanced_options
      # ref: refs/tags/5.2.0
    - repository: iam-controls
      type: git
      name: DEVOPS_Platform_as_a_Service/iam-controls
      #ref: refs/tags/2.33.0
      ref: AB#507871-replace-template_file
    - repository: efs
      type: git
      name: DEVOPS_Platform_as_a_Service/efs
      ref: refs/tags/5.3.2
    - repository: ec2
      type: git
      name: DEVOPS_Platform_as_a_Service/ec2
      ref: refs/tags/6.15.0
      # Testing AB#304688-create-alarm-for-failed-backups
      # - repository: secret_kms_key_module
      # type: git
      # name: DEVOPS_Platform_as_a_Service/secret_kms_key_module
      # ref: refs/tags/1.0.0
      #- repository: rds-mysql-v2
      #type: git
      #name: DEVOPS_Platform_as_a_Service/rds-mysql-v2
      #ref: refs/tags/7.0.0
    - repository: security-groups
      type: git
      name: DEVOPS_Platform_as_a_Service/security-groups
      ref: refs/tags/2.36.1
      #- repository: DocumentDB
      #type: git
      #name: DEVOPS_Platform_as_a_Service/DocumentDB
      #ref: refs/tags/2.1.0
      #- repository: AWS-SQS
      #type: git
      #name: DEVOPS_Platform_as_a_Service/AWS-SQS
      #ref: AB#433757-add-s3-access
      #- repository: transfer-family-service-managed
      #type: git
      #name: DEVOPS_Platform_as_a_Service/transfer-family-service-managed
      #ref: refs/tags/4.0.0
      # ref: refs/tags/1.6.0
      #- repository: fsx
      #type: git
      #name: DEVOPS_Platform_as_a_Service/Amazon-FSx
      #ref: AB#344844-support-self-hosted-AD
      # ref: refs/tags/2.0.0
      # - repository: openzfs
      # type: git
      # name: DEVOPS_Platform_as_a_Service/OpenZFS-FSx
      # ref: AB#344844-initial-OpenZFS-support-v1-and-vpce
      # ref: refs/tags/1.0.0
      # - repository: PySRE
      #type: git
      #name: SAMC Shared Components/PySRE
      #ref: refs/tags/1.0.0
    - repository: secret-manager
      type: git
      name: DEVOPS_Platform_as_a_Service/secret-manager
      ref: refs/tags/1.1.0
      # - repository: patch-manager
      # type: git
      # name: DEVOPS_Platform_as_a_Service/patch-manager
      # ref: refs/tags/1.1.0
      # - repository: rds-proxy
        # type: git
        # name: DEVOPS_Platform_as_a_Service/rds-proxy
        # ref: AB#276745-initial-version-with-dashboard

trigger: none

variables:
  pipelineSrcDirectory: 'terraform'

parameters:
- name: terrformPLANonly
  displayName: tfPlanOnly (check == true)
  type: boolean
  default: false

stages:
  - template: deploy/tf-create-infra-template.yml@templates
    parameters:
      environment: sandbox
      environmentDisplayName: Sandbox
      tfServiceConnection: DevopsSandbox-889050139813-DevopsIACSvcVpc-us-east-1
      awsServiceConnection: DevopsSandbox-889050139813-DevopsIACSvcVpc
      tfVersion: 1.12.2
      application: PlatformEng
      pipelineSrcDir: $(Build.Repository.Name)
      tfPlanOnly: ${{ parameters.terrformPLANonly }}
      reqRDSauroraPg: true
      customer: Thompson-Inc
      regionName: us-east-1
      reqEKSGRule: true
      reqEKSMod: false
      folderToZip: PySRE
      # DataDogApiKey: NTVmOWUxMWY1ZDczODMxZjlmNGFhZGNhOGE3M2JkZjc=
      # DDRandomToken: cExuQjVGM0N4UzJYRGtqQTA5N0J6WG1ONU5hdGVSbHo=
      reqMongoMod: true
      reqSSRS: false
      reqRDSmssqlMod: true
      reqRDSaurora: false
      reqAmazonMQMod: true
      checkoutTemplate: NatesCheckouts.yml
      fluxVersion: '1.25.4'
      fluxCIDir: flux-app-sandbox
      fluxRepoBranch: AB#241049-test-ZNathanT-EFS
      project: DEVOPS_Platform_as_a_Service
      reqRDSmysqlMod: true
      reqDocDB: true
      allow_ASG_BeanStalk_access: true
      # Shared_Environment: true
      # SourceAccountID: 116395083606
      # DBRefresh: true
