# Purpose: PLAN-DESTROY/DESTROY the Sandbox stack for rds-aurora
# Run: Pipelines → Run → tfPlanOnly=true for preview, false to destroy

resources:
  repositories:
    - repository: templates
      type: git
      name: DEVOPS_Platform_as_a_Service/deploy-templates
      ref: refs/tags/7.2.0

    # Keep the same set of shared repos pinned (mirrors create pipeline)
    - repository: alarm-aggregator
      type: git
      name: DEVOPS_Platform_as_a_Service/alarm-aggregator
      ref: refs/tags/2.0.3
    - repository: sns-subtopic
      type: git
      name: DEVOPS_Platform_as_a_Service/sns-subtopic
      ref: refs/tags/2.0.1
    - repository: vpc
      type: git
      name: DEVOPS_Platform_as_a_Service/vpc
      ref: refs/tags/4.1.1
    - repository: nlb
      type: git
      name: DEVOPS_Platform_as_a_Service/nlb
      ref: refs/tags/1.7.0
    - repository: API-Gateway
      type: git
      name: DEVOPS_Platform_as_a_Service/API-Gateway
      ref: refs/tags/1.1.0
    - repository: mongodb
      type: git
      name: DEVOPS_Platform_as_a_Service/mongodb
      ref: refs/tags/5.8.0
    - repository: mongodb-v7
      type: git
      name: DEVOPS_Platform_as_a_Service/mongodb-v7
      ref: AB#547831-Sept-2025-update-AMI
    - repository: s3
      type: git
      name: DEVOPS_Platform_as_a_Service/s3
      ref: refs/tags/4.2.0
    - repository: amazonmq
      type: git
      name: amazonmq
      ref: refs/tags/4.2.0
    - repository: lambdas
      type: git
      name: DEVOPS_Platform_as_a_Service/lambdas
      ref: refs/tags/3.2.0
    - repository: eks-cluster-v11
      type: git
      name: DEVOPS_Platform_as_a_Service/eks-cluster-v11
      ref: refs/tags/3.7.0
    - repository: ssrs-rdsmssql
      type: git
      name: DEVOPS_Platform_as_a_Service/ssrs-rdsmssql
      ref: refs/tags/13.0.0
    - repository: rds-mssql
      type: git
      name: DEVOPS_Platform_as_a_Service/rds-mssql
      ref: refs/tags/12.0.0
    - repository: iam-controls
      type: git
      name: DEVOPS_Platform_as_a_Service/iam-controls
      ref: AB#507871-replace-template_file
    - repository: efs
      type: git
      name: DEVOPS_Platform_as_a_Service/efs
      ref: refs/tags/5.3.2
    - repository: ec2
      type: git
      name: DEVOPS_Platform_as_a_Service/ec2
      ref: refs/tags/6.15.0
    - repository: security-groups
      type: git
      name: DEVOPS_Platform_as_a_Service/security-groups
      ref: refs/tags/2.36.1
    - repository: secret-manager
      type: git
      name: DEVOPS_Platform_as_a_Service/secret-manager
      ref: refs/tags/1.1.0

trigger: none

variables:
  pipelineSrcDirectory: ""   # repo root

parameters:
- name: terrformPLANonly
  displayName: tfPlanOnly (true=plan only, false=destroy)
  type: boolean
  default: true

stages:
  - template: destroy/tfdestroy-template.yml@templates
    parameters:
      environment: sandbox
      environmentDisplayName: Sandbox
      regionName: us-east-1

      tfServiceConnection: DevopsSandbox-889050139813-DevopsIACSvcVpc-us-east-1
      awsServiceConnection: DevopsSandbox-889050139813-DevopsIACSvcVpc

      tfVersion: 1.12.2
      application: PlatformEng
      pipelineSrcDir: $(Build.Repository.Name)
      tfPlanOnly: ${{ parameters.terrformPLANonly }}

      # Match toggles with what was deployed
      reqRDSauroraPg: true
      reqRDSaurora: false
      reqRDSmssqlMod: false
      reqRDSmysqlMod: false
      reqMongoMod: false
      reqDocDB: false
      reqAmazonMQMod: false
      reqSSRS: false
      reqEKSGRule: false
      reqEKSMod: false

      checkoutTemplate: NatesCheckouts.yml
      customer: Thompson-Inc
